(function initConfig(root) {
  'use strict';

  const config = {
    version: 3,
    title: '华夏人生',
    storageKey: 'huaxia-life:v1',
    startYear: 2026,
    startMonth: 7,
    locations: [
      ['北京', '北京'], ['上海', '上海'], ['广东', '深圳'], ['四川', '成都'],
      ['湖北', '武汉'], ['陕西', '西安'], ['浙江', '杭州'], ['江苏', '南京'],
      ['山东', '青岛'], ['云南', '昆明'], ['辽宁', '沈阳'], ['福建', '厦门'],
      ['河南', '郑州'], ['湖南', '长沙'], ['黑龙江', '哈尔滨'],
    ],
    cities: [
      { city: '北京', province: '北京', tier: 1, cost: 18000 },
      { city: '上海', province: '上海', tier: 1, cost: 18000 },
      { city: '深圳', province: '广东', tier: 1, cost: 16000 },
      { city: '杭州', province: '浙江', tier: 1, cost: 14000 },
      { city: '南京', province: '江苏', tier: 2, cost: 11000 },
      { city: '成都', province: '四川', tier: 2, cost: 9000 },
      { city: '武汉', province: '湖北', tier: 2, cost: 9000 },
      { city: '西安', province: '陕西', tier: 2, cost: 8500 },
      { city: '长沙', province: '湖南', tier: 2, cost: 8000 },
      { city: '青岛', province: '山东', tier: 2, cost: 9000 },
      { city: '厦门', province: '福建', tier: 2, cost: 10000 },
      { city: '昆明', province: '云南', tier: 3, cost: 6500 },
      { city: '沈阳', province: '辽宁', tier: 3, cost: 6500 },
      { city: '郑州', province: '河南', tier: 3, cost: 7000 },
      { city: '哈尔滨', province: '黑龙江', tier: 3, cost: 6500 },
    ],
    surnames: ['李', '王', '张', '刘', '陈', '杨', '赵', '黄', '周', '吴', '徐', '孙'],
    givenNames: ['安然', '星河', '知夏', '景行', '雨桐', '子衿', '明远', '若溪', '嘉禾', '清越'],
    parentJobs: ['教师', '会计', '工程师', '医生', '店主', '司机', '公务员', '设计师', '厨师'],
    personalities: ['内向', '外向', '傲娇', '温柔', '理性', '热血', '慢热', '乐观'],
    traits: ['好奇', '细心', '勇敢', '敏感', '自律', '随和', '执着', '幽默', '务实', '浪漫'],
    appearance: {
      hairColor: ['黑色', '深棕', '栗色', '亚麻棕', '银灰', '黑灰'],
      temperament: ['懵懂', '童真', '清朗', '青涩', '明快', '沉稳', '从容', '温和', '清冷', '文雅', '干练', '灵动'],
      bodyType: ['幼小', '清瘦', '匀称', '健壮', '丰润'],
      hairstyle: ['胎毛短发', '儿童短发', '清爽短发', '齐肩直发', '高马尾', '层次碎发', '自然层次发', '自然卷发', '利落短发', '简约短发', '银丝短发'],
      top: ['婴儿连体衣', '彩色童装', '简洁校服', '校园休闲', '运动穿搭', '文艺穿搭', '通勤正装', '品质日常', '舒适棉麻', '针织开衫', '工装外套', '轻便羽绒服'],
      socks: ['婴儿袜', '短棉袜', '白色中筒袜', '船袜', '运动袜', '黑色商务袜', '羊毛袜'],
      shoes: ['婴儿软底鞋', '魔术贴童鞋', '白色运动鞋', '帆布鞋', '跑步鞋', '乐福鞋', '皮鞋', '舒适布鞋'],
    },
    stages: [
      { max: 2, name: '幼儿期' }, { max: 5, name: '幼儿园' },
      { max: 11, name: '小学' }, { max: 14, name: '初中' },
      { max: 17, name: '高中' }, { max: 21, name: '大学' },
      { max: 59, name: '职场人生' }, { max: 200, name: '从心之年' },
    ],
    subjectCaps: {
      primary: { 语文: 100, 数学: 100, 英语: 100, 科学: 100 },
      middle: { 语文: 130, 数学: 130, 英语: 130, 政治: 50, 历史: 50, 物理: 100, 化学: 100 },
      highBase: { 语文: 150, 数学: 150, 英语: 150 },
    },
    highSchools: [
      { suffix: '第一中学', min: 560, type: '省级示范' },
      { suffix: '实验中学', min: 500, type: '市级重点' },
      { suffix: '新区高级中学', min: 420, type: '公办普通' },
      { suffix: '综合高级中学', min: 280, type: '综合高中' },
    ],
    universities: [
      { name: '华夏大学', min: 675, major: '计算机科学', type: '顶尖综合', city: '北京' },
      { name: '东海交通大学', min: 650, major: '智能制造', type: '985', city: '上海' },
      { name: '南方科技大学', min: 630, major: '数据科学', type: '双一流', city: '深圳' },
      { name: '江南医科大学', min: 615, major: '临床医学', type: '医科重点', city: '南京' },
      { name: '西京政法大学', min: 595, major: '法学', type: '211', city: '西安' },
      { name: '东海财经大学', min: 580, major: '金融学', type: '财经重点', city: '上海' },
      { name: '南山师范大学', min: 545, major: '教育学', type: '一本', city: '长沙' },
      { name: '江城理工大学', min: 510, major: '建筑工程', type: '一本', city: '武汉' },
      { name: '锦华传媒学院', min: 465, major: '数字媒体', type: '二本', city: '成都' },
      { name: '滨海商学院', min: 430, major: '工商管理', type: '民办本科', city: '青岛' },
      { name: '春城应用学院', min: 390, major: '现代服务', type: '应用本科', city: '昆明' },
      { name: '城市职业学院', min: 280, major: '机电技术', type: '高职专科', city: '郑州' },
    ],
    jobs: [
      { id: 'software', name: '软件工程师', salary: 12500, need: 72, category: '科学', majors: ['计算机科学', '数据科学'], tier: 2 },
      { id: 'algorithm', name: '算法工程师', salary: 19000, need: 88, category: '科学', majors: ['计算机科学', '数据科学'], tier: 1 },
      { id: 'data', name: '数据分析师', salary: 11000, need: 75, category: '科学', majors: ['数据科学', '金融学'], tier: 2 },
      { id: 'product', name: '产品经理', salary: 13500, need: 78, category: '社交', majors: ['计算机科学', '工商管理'], tier: 1 },
      { id: 'finance', name: '金融分析师', salary: 14500, need: 82, category: '商业', majors: ['金融学'], tier: 1 },
      { id: 'bank', name: '银行客户经理', salary: 9200, need: 65, category: '商业', majors: ['金融学', '工商管理'], tier: 3 },
      { id: 'doctor', name: '住院医师', salary: 10800, need: 86, category: '科学', majors: ['临床医学'], tier: 2 },
      { id: 'teacher', name: '中学教师', salary: 7800, need: 68, category: '文学', majors: ['教育学'], tier: 3 },
      { id: 'lawyer', name: '律师助理', salary: 8500, need: 74, category: '文学', majors: ['法学'], tier: 2 },
      { id: 'civil', name: '基层公务员', salary: 7200, need: 76, category: '文学', majors: ['法学', '工商管理'], tier: 3 },
      { id: 'architect', name: '建筑设计师', salary: 11200, need: 76, category: '艺术', majors: ['建筑工程'], tier: 2 },
      { id: 'engineer', name: '制造工程师', salary: 9800, need: 70, category: '科学', majors: ['智能制造', '机电技术'], tier: 3 },
      { id: 'designer', name: '视觉设计师', salary: 9000, need: 67, category: '艺术', majors: ['数字媒体'], tier: 2 },
      { id: 'planner', name: '游戏策划', salary: 9600, need: 70, category: '艺术', majors: ['数字媒体', '计算机科学'], tier: 1 },
      { id: 'journalist', name: '新媒体编辑', salary: 7200, need: 60, category: '文学', majors: ['数字媒体'], tier: 3 },
      { id: 'operator', name: '运营专员', salary: 7000, need: 55, category: '社交', majors: ['工商管理', '现代服务'], tier: 3 },
      { id: 'sales', name: '销售顾问', salary: 6500, need: 48, category: '社交', majors: [], tier: 3 },
      { id: 'logistics', name: '物流调度员', salary: 6200, need: 48, category: '商业', majors: ['现代服务'], tier: 3 },
      { id: 'chef', name: '餐饮主厨', salary: 7200, need: 52, category: '艺术', majors: ['现代服务'], tier: 3 },
      { id: 'photo', name: '商业摄影师', salary: 8000, need: 62, category: '艺术', majors: ['数字媒体'], tier: 2 },
      { id: 'socialwork', name: '社区工作者', salary: 5600, need: 45, category: '社交', majors: ['教育学', '现代服务'], tier: 3 },
      { id: 'electrician', name: '机电技术员', salary: 6800, need: 50, category: '科学', majors: ['机电技术'], tier: 3 },
      { id: 'freelance', name: '自由职业者', salary: 5200, need: 35, category: '艺术', majors: [], tier: 3 },
    ],
    houses: [
      { name: '城市单身公寓', price: 320000, comfort: 6 },
      { name: '近郊两居室', price: 680000, comfort: 12 },
      { name: '市中心三居室', price: 1380000, comfort: 20 },
    ],
    stocks: { 华夏科技: 32.4, 民生消费: 18.6, 绿色能源: 24.8 },
  };

  root.LifeGame = root.LifeGame || {};
  root.LifeGame.config = Object.freeze(config);
}(window));
